# SonarCloud Configuration
# This file is used by the SonarScanner to configure analysis.

# Project metadata
sonar.projectKey=turbo-diesel-skeletoni
sonar.projectName=skeletoni

# Exclusions
# We exclude local configuration templates and files to avoid "Credential Disclosure" false positives.
sonar.exclusions=**/application-local.yml, **/application-local.yml.example, **/target/**, .idea/**, .mvn/**
